name: 'release'

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: 'write'
  packages: 'write'

jobs:
  release:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'docker/setup-qemu-action@v2'

      - uses: 'actions/checkout@v3'
        with:
          fetch-depth: 0

      - uses: 'actions/setup-go@v3'
        with:
          go-version: '1.19'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: 'goreleaser/goreleaser-action@v3'
        with:
          version: 'latest'
          args: 'release --rm-dist'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
